resources:
  - name: sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:
  - name: pipeline
    steps:
      - name: step
        type: bash
        triggeredBy:
          resources:
            - sample_node
        execution:
          onExecute:
            - echo "executing test bash step..."
