resources:
  - name: app1
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:

  - name: test_pipeline
    steps:
      - name: test_func
        type: bash
        configuration:
          affinityGroup: build
          nodePool: kermit_centos_pool
        setup:
          environmentVariables:
            normal:
              myFirstName: ANKUL
              myLastName: KUMAR
            encrypted:
              myMiddleName: P0MA0FvspdmtybGshqsaGHwisg+oSu8DcLA7biLiZGhoSgrKpua4yZHqy5dWPakhUXZrvqd/TQGGR6TvIFqKcPrkG1aCzhVIScDL6ZuWGgvoUKqeAyppnAnRMh17t2hCmpvgJrd9+hmeqRprGL+CBsDnzpjQ4plIogt4tPpJq8CnDqMVTzKvVuafJhPen7fBDCJ/SuK1co7cdDoayziNI8ARFvWVSBt2OEE73qtsOK66F+Jm51R/HKJplCSl1/CVbJepVXf3uFoC6WOBygv7fpSxaPSrV60JIt02CYfstVlWFk48oKcmaJcldRbMmlhBHiGjdX9VduGUF7QTQNDE8w==
        requires:
          resources:
            - app1
          integrations:
            - art
        execution:
          onExecute:
            - echo $myFirstName
            - echo $myLastName
            - echo $myMiddleName
            - printenv


      - name: test_func_next
        type: bash
        configuration:
          affinityGroup: build
          nodePool: kermit_centos_pool
        triggeredBy:
          steps:
            - test_func
        execution:
          onExecute:
            - printenv


      - name: parallel_1
        type: bash
        triggeredBy:
          steps:
            - test_func_next
        execution:
          onExecute:
            - printenv
            - echo $imageTag


      - name: parallel_2
        type: bash
        triggeredBy:
          steps:
            - test_func_next
        execution:
          onExecute:
            - printenv

      - name: parallel_3
        type: bash
        triggeredBy:
          steps:
            - test_func_next
        execution:
          onExecute:
            - printenv

      - name: final_step
        type: bash
        triggeredBy:
          steps:
            - parallel_2
            - parallel_1
            - parallel_3
        execution:
          onExecute:
            - printenv
