resources:
  - name: sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
      branches:
        except: random
    initialVersion:
      sha: master   

pipelines:
  - name: pipeline_1
    steps:
      - name: step_1
        type: bash
        triggeredBy:
          resources:
            - sample_node
        execution:
          onExecute:
            - echo "executing test bash step_1..."

      - name: step_2
        type: bash
        triggeredBy:
          resources:
            - sample_node
          steps:
            - step_1
        execution:
          onExecute:
            - echo "executing test bash step_2..."            
            
