resources:
  - name: file_res_1
    type: file
    configuration:
      integrationName: ankul_artifactory
    initialVersion:
      fileLocation: " example-repo-local"
      fileName: "archive.zip"
   
  - name: file_res_2
    type: file
    configuration:
      integrationName: ankul_artifactory
    initialVersion:
      pattern: "ragesh-generic/test-foo*.txt"
      
pipelines:
  - name: ankul_pipeline
    steps:
      - name: build_step
        type: bash
        configuration:
          affinityGroup: test
          nodePool: ankul_nodes
        triggeredBy:
          resources:
            - file_res_1
            - file_res_2
        execution:
          onExecute:
            - printenv
            - sudo apt-get install tree
            - tree $res_file_res_1_resourcePath
            - tree $res_file_res_2_resourcePath
            - cat $STEP_TMP_DIR/fileSpecs.json
 
      - name: push_step
        type: push
        configuration:
          affinityGroup: test
          nodePool: ankul_nodes
        setup:
          push:
            targetRepo: ankul_local_repo
        requires:
          integrations:
            - ankul_artifactory
        triggeredBy:
          steps:
            - build_step
