resources:
  - name: sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
      branches:
        except: random
    initialVersion:
      sha: master   

pipelines:
  - name: pipeline_1
    steps:
      - name: step_1
        type: bash
        setup:
          environmentVariables:
            normal:
              ENV3: value3
              ENV4: value4
        triggeredBy:
          resources:
            - sample_node
          steps:
            - step_2
        execution:
          onExecute:
            - echo "executing test bash step_1..."

      - name: step_2
        type: bash
        setup:
          environmentVariables:
            normal:
              ENV5: value5
              ENV6: value6       
        triggeredBy:
          resources:
            - sample_node 
          steps:
            - step_1
        execution:
          onExecute:
            - echo "executing test bash step_2..."            
            
