resources:
  - name: file_res_1
    type: file
    configuration:
      integrationName: ankul_artifactory
    initialVersion:
      fileLocation: " example-repo-local"
      fileName: "archive.zip"
   
  - name: file_res_2
    type: file
    configuration:
      integrationName: ankul_artifactory
    initialVersion:
      pattern: "demo/app/"
      flat: false
      recursive: true
      target: "ankul_local_repo/"
      limit: 5
      offset: 5
      
pipelines:
  - name: ankul_pipeline
    steps:
      - name: step_1
        type: bash
        configuration:
          nodePool: ankul_nodes
        triggeredBy:
          resources:
            - file_res_1
            - file_res_2
        execution:
          onExecute:
            - printenv
            - sudo apt-get install tree
            - tree $res_file_res_1_resourcePath
            - tree $res_file_res_2_resourcePath
            - cat $STEP_TMP_DIR/fileSpecs.json
            - echo test_3
