pipelines:
  - name: pipeline_1
    steps:
      - name: step_1
        type: bash
        execution:
          onExecute:
            - echo "executing test bash step_1..."
   
      - name: step_2
        type: bash
        triggeredBy:
          steps:
            - step_1
        execution:
          onExecute:
            - echo "executing test bash step_2..."
            
      - name: step_3
        type: bash
        configuration:
          affinityGroup: test_group
        triggeredBy:
          steps:
            - step_1
        execution:
          onExecute:
            - echo "executing test bash step_3..."
            
      - name: step_4
        type: bash
        configuration:
          affinityGroup: test_group        
        triggeredBy:
          steps:
            - step_3
        execution:
          onExecute:
            - echo "executing test bash step_4..."            
          
