resources:
  - name: sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
      branches:
        except: random
    initialVersion:
      sha: master   

pipelines:
  - name: pipeline_1
    steps:
      - name: step_1
        type: bash
        setup:
          environmentVariables:
            normal:
              ENV3: value3
              ENV4: value4
        triggeredBy:
          resources:
            - sample_node
        execution:
          onExecute:
            - echo "executing test bash step_1..."
        outputResources:
          - sample_node
