resources:
  - name: invalid_yml
    type: releaseBundle
    version:
      name: something
      version: 12
      isSigned: 213
      dsaas: 123
      
  - name: valid_1
    type: releaseBundle
    version:
      name: something
      
  - name: valid_2
    type: releaseBundle
    version:
      name: something
      version: asdsa23
      isSigned: true

pipelines:
  - name: ankul_pipeline_2
    steps:
      - name: step_1
        type: bash
        configuration:
          nodePool: ankul_nodes  
        requires:
          resources:
            - valid_1
            - valid_2
        execution:
          onExecute:
            - sleep 1
 
