resources:
  - name: files
    type: file
    configuration:
      integrationName: ankul_artifactory
    version:
      pattern: "demp/app/"
   
  - name: sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
    version:
      sha: "master"
      
pipelines:
  - name: ankul_pipeline
    steps:
      - name: build
        type: build
        configuration:
          affinityGroup: test
          nodePool: ankul_nodes
        payloadType: docker
        setup:
          build:
            dockerFileLocation: .
            dockerFileName: Dockerfile
            imageName: 34.66.110.173/docker-local/ankul
            imageTag: $PIPELINE_NAME.$RUN_NUMBER
        requires:
          integrations:
            - ankul_artifactory
          resources:
            - sample_node
            - files
 
#       - name: push_step
#         type: push
#         configuration:
#           affinityGroup: test
#           nodePool: ankul_nodes
#         setup:
#           push:
#             targetRepo: ankul_local_repo
#         requires:
#           integrations:
#             - ankul_artifactory
#         triggeredBy:
#           steps:
#             - build_step
