resources:
  - name: app1
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
      branches:
        only: master
    initialVersion:
      sha: master

pipelines:

  - name: test_pipeline
    steps:
      - name: test_func
        type: bash
        configuration:
          affinityGroup: build
          nodePool: ankul_u16_nodes
        setup:
          environmentVariables:
            normal:
              myFirstName: ANKUL
              myLastName: KUMAR
              myMiddleName: NONE
          resources:
            - app1
          integrations:
            - art
        execution:
          onExecute:
            - echo $myFirstName
            - echo $myLastName
            - echo $myMiddleName
            - printenv


      - name: test_func_next
        type: bash
        configuration:
          affinityGroup: build
          nodePool: ankul_u16_nodes
        triggeredBy:
          steps:
            - test_func
        execution:
          onExecute:
            - printenv


      - name: parallel_1
        type: bash
        triggeredBy:
          steps:
            - test_func_next
        execution:
          onExecute:
            - printenv
            - echo $imageTag


      - name: parallel_2
        type: bash
        triggeredBy:
          steps:
            - test_func_next
        execution:
          onExecute:
            - printenv

      - name: parallel_3
        type: bash
        triggeredBy:
          steps:
            - test_func_next
        execution:
          onExecute:
            - printenv

      - name: final_step
        type: bash
        triggeredBy:
          steps:
            - parallel_2
            - parallel_1
            - parallel_3
        execution:
          onExecute:
            - printenv
