resources:
  - name: file_res_1
    type: file
    configuration:
      integrationName: ankul_artifactory
    initialVersion:
      fileLocation: " example-repo-local"
      fileName: "archive.zip"
   
  - name: file_res_2
    type: file
    configuration:
      integrationName: ankul_artifactory
    initialVersion:
      pattern: "demo/app/"
      flat: true
      
pipelines:
  - name: ankul_pipeline
    steps:
      - name: step_1
        type: bash
        configurations:
          nodePool: ankul_nodes
        triggeredBy:
          resources:
            - file_res_1
            - file_res_2
        execution:
          onExecute:
            - printenv
            - ls $res_file_res_1_resourcePath
            - ls $res_file_res_2_resourcePath
