resources:
  - name: invalid_yml
    type: aql
    version:
      query: something
      sdad: asdsad
      
  - name: valid_1
    type: releaseBundle
    version:
      name: something
      version: v1.10.0
      
  - name: valid_2
    type: releaseBundle
    version:
      name: something
      version: asdsa23
      isSigned: true

pipelines:
  - name: ankul_pipeline_2
    steps:
      - name: step_1
        type: bash
        configuration:
          nodePool: ankul_nodes  
        requires:
          resources:
            - valid_1
            - valid_2
            - invalid_yml
        execution:
          onExecute:
            - sleep 1
 
