resources:      
#   - name: file
#     type: file
#     fileLocation: s3://strangers-beta/profiles
#     fileName: 1.png
#     configuration:
#       integrationName: ankul_aws
#     initialVersion:
#       fileDtTm: "2019-01-06" 
      
  - name: sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
    initialVersion:
      sha: master   

pipelines:
  - name: ankul_pipeline
    steps:
      - name: step_1
        type: bash
        triggeredBy:
          resources:
            - sample_node
        execution:
          onExecute:
            - printenv
          
      - name: step_2
        type: bash
        triggeredBy:
          resources:
            - sample_node
        execution:
          onExecute:
            - printenv
