resources:
  - name: sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
    initialVersion:
      sha: master

  - name: file_res_jTest
    type: file
    fileLocation: https://raw.githubusercontent.com/ChaitanyaVootla/jfrogTest/master/test.yml
    fileName: shippable.yml
    configuration:
      integrationName: ankul_github
    initialVersion:
      fileDtTm: random_value

  - name: image_res_jTest
    type: image
    imageName: "library/nginx"
    configuration:
      integrationName: ankul_github
    initialVersion:
      imageTag: latest

  - name: stateResource_jTest
    type: state

  - name: webhookRes_jTest
    type: webhook
    configuration:
      integrationName: ankul_github
    initialVersion:
      payload: "asd"
  
pipelines:
  - name: jTest_pipeline
    setup:
      runtime: onHost
    steps:
      - name: step_jTest
        type: bash
        configuration:
          affinityGroup: test_group
        setup:
          runtime:
            type: image
            image:
              auto:
                language: java
                versions:
                  - 10.10.10
        requires:
          integrations:
            - ankul_github
          resources:
            - stateResource_jTest
        triggeredBy:
          resources:
            - sample_node
            - webhookRes_jTest
        execution:
          onExecute:
            - echo "executing..."
        outputResources:
          - file_res_jTest
          - stateResource_jTest
          - image_res_jTest
          
      - name: img_test_push
        type: bash
        triggeredBy:
          steps:
            - step_jTest
        execution:
          onExecute:
            - printenv
            - write_output image_res_jTest imageTag=master
        outputResources:
          - image_res_jTest
      - name: img_read
        type: bash
        execution:
          onExecute:
            - printenv
        triggeredBy:
          resources:
            - image_res_jTest
            
            
      - name: img_test_push_2
        type: bash
        requires:
          resources:
            - image_res_jTest
        execution:
          onExecute:
            - printenv
            - write_output image_res_jTest imageTag=master
        

  - name: ankul_pipelines_2
    steps:
      - name: step_1
        type: bash
        requires:
          resources:
            - image_res_jTest
        execution:
          onExecute:
            - printenv
