pipelines:
  - name: ankul_pipeline_2
    steps:
      - name: step_1
        type: bash
        execution:
          onExecute:
            - sleep 180
   
      - name: step_2
        type: bash
        triggeredBy:
          steps:
            - step_1
        execution:
          onExecute:
            - sleep 180

  - name: ankul_pipeline_3
    steps:
      - name: step_3
        type: bash
        execution:
          onExecute:
            - sleep 180
   
      - name: step_4
        type: bash
        triggeredBy:
          steps:
            - step_3
        execution:
          onExecute:
            - sleep 180
