pipelines:
  - name: ankul_pipeline_2
    steps:
      - name: step_1
        type: bash
        configuration:
          nodePool: ankul_nodes
        execution:
          onExecute:
            - sleep 1
   
      - name: step_2
        type: bash
        configuration:
          nodePool: ankul_nodes        
        triggeredBy:
          steps:
            - step_1
        execution:
          onExecute:
            - sleep 10

      - name: step_3
        type: bash
        configuration:
          nodePool: ankul_nodes        
        triggeredBy:
          steps:
            - step_1        
        execution:
          onExecute:
            - sleep 120
   
      - name: step_4
        type: bash
        configuration:
          nodePool: ankul_nodes        
        triggeredBy:
          steps:
            - step_2
            - step_3
        execution:
          onExecute:
            - sleep 1
