resources:
  - name: file_res_in
    type: file
    configuration:
      integrationName: art
    initialVersion:
      fileLocation: "string"
      fileName: "string"
   
  - name: file_res_out
    type: file
    configuration:
      integrationName: art
    initialVersion:
      fileDtTm: "random "
      pattern: "string"
      aql: "string"
      target: "string"
      props: "string"
      recursive: true
      flat: false
      excludePatterns: "string"
      archiveEntries: "string"
      build: "string"
      sortBy: "string"
      sortOrder: "string"
      limit: 2
      offset: 12
      
pipelines:
  - name: ankul_pipeline
    steps:
      - name: step_1
        type: bash
        triggeredBy:
          resources:
            - file_res_in
        execution:
          onExecute:
            - echo "executing step_1..."
        outputResources:
            - file_res_out
