resources:
  - name: files
    type: file
    configuration:
      integrationName: ankul_artifactory
    version:
      pattern: "example-repo-local/"
   
  - name: sample_node
    type: gitRepo
    repoPath: ankul-shippable/sample_node
    configuration:
      integrationName: ankul_github
    version:
      sha: "master"
      
  - name: promoteInfo
    type: buildInfo
    version:
      buildName: bar
      buildNumber: 2 
      
  - name: info
    type: buildInfo
    version:
      buildName: foo
      buildNumber: 1        
      
pipelines:
  - name: ankul_pipeline
    steps:
      - name: build
        type: build
        configuration:
          affinityGroup: test
          nodePool: ankul_nodes
        payloadType: docker
        setup:
          build:
            dockerFileLocation: .
            dockerFileName: Dockerfile
            imageName: 34.66.110.173:8081/docker-local/ankul
            imageTag: $PIPELINE_NAME.$RUN_NUMBER
        requires:
          integrations:
            - ankul_artifactory
          resources:
            - sample_node
            - files
        execution:
          onStart:
            - sudo apt-get install tree
            - tree /tmp/jfrog
          onComplete:
            - tree /tmp/jfrog

      - name: push
        type: push
        configuration:
          affinityGroup: test
          nodePool: ankul_nodes
        setup:
          push:
            targetRepo: docker-local
        requires:
          integrations:
            - ankul_artifactory
        triggeredBy:
          steps:
            - build
        execution:
          onStart:
            - sudo apt-get install tree
            - tree /tmp/jfrog
          onComplete:
            - tree /tmp/jfrog
            - buildName=$(eval echo "$""$buildStepName"_buildName)
            - buildNumber=$(eval echo "$""$buildStepName"_buildNumber)
            - jfrog rt bp ankul-pipeline $buildName $buildNumber
            
      - name: publish
        type: publish
        configuration:
          affinityGroup: test
          nodePool: ankul_nodes
        requires:
          resources:
            - sample_node
          integrations:
            - ankul_artifactory
#         triggeredBy:
#           steps:
#             - push
        outputResources:
          - info
        execution:
          onStart:
            - sudo apt-get install tree
            - tree /tmp/jfrog
          onComplete:
            - tree /tmp/jfrog          

      - name: promote
        type: promote
        configuration:
          affinityGroup: test
          nodePool: ankul_nodes
        setup:
          promote:
            targetRepo: ankul_local_repo    
        requires:
          integrations:
            - ankul_artifactory         
        triggeredBy:
          resources:
            - info
        outputResources:
          - promoteInfo
