resources:
  - name: state
    type: state
    initialVersion:
      RANDOM_KEY: random_value
      

pipelines:
  - name: pipeline_1
    steps:
      - name: step_1
        type: bash
        triggeredBy:
          resources:
            - state
        execution:
          onExecute:
            - echo "executing test bash step_1..."
        outputResources:
          - state
            
      - name: step_2
        type: bash
        triggeredBy:
          resources:
            - state
        execution:
          onExecute:
            - echo "executing test bash step_2..."  
        outputResources:
          - state
